version: "2"

services:
    serve:
        image: node:alpine
        volumes:
            - ./:/usr/src/app
        environment:
            - NPM_CONFIG_LOGLEVEL warn
            - NODE_ENV=production
        expose:
            - "8080"

    local:
        build: .
        volumes:
            - ./:/usr/src/app
        environment:
            - NPM_CONFIG_LOGLEVEL warn
