version: "2"

services:
    docker-node:
        build: .
        volumes:
            - .:/usr/src/app
        environment:
            - NPM_CONFIG_LOGLEVEL warn
            - NODE_ENV=production
        expose:
            - "8080"
